export const RECEIPE_LIST_REQUEST = "RECEIPE_LIST_REQUEST";
export const RECEIPE_LIST_FAIL = "RECEIPE_LIST_FAIL";
export const RECEIPE_LIST_SUCCESS = "RECEIPE_LIST_SUCCESS";

export const RECEIPE_LIST_BY_ID_REQUEST = "RECEIPE_LIST_BY_ID_REQUEST";
export const RECEIPE_LIST_BY_ID_FAIL = "RECEIPE_LIST_BY_ID_FAIL";
export const RECEIPE_LIST_BY_ID_SUCCESS = "RECEIPE_LIST_BY_ID_SUCCESS";
